# Generated by Django 5.0.14 on 2025-10-14 16:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=10)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_view', models.BooleanField(default=False, verbose_name='Students View')),
                ('students_edit', models.BooleanField(default=False, verbose_name='Students Edit')),
                ('teachers_view', models.BooleanField(default=False, verbose_name='Teachers View')),
                ('teachers_edit', models.BooleanField(default=False, verbose_name='Teachers Edit')),
                ('fees_view', models.BooleanField(default=False, verbose_name='Fees View')),
                ('fees_edit', models.BooleanField(default=False, verbose_name='Fees Edit')),
                ('payments_view', models.BooleanField(default=False, verbose_name='Payments View')),
                ('payments_edit', models.BooleanField(default=False, verbose_name='Payments Edit')),
                ('attendance_view', models.BooleanField(default=False, verbose_name='Attendance View')),
                ('attendance_edit', models.BooleanField(default=False, verbose_name='Attendance Edit')),
                ('transport_view', models.BooleanField(default=False, verbose_name='Transport View')),
                ('transport_edit', models.BooleanField(default=False, verbose_name='Transport Edit')),
                ('reports_view', models.BooleanField(default=False, verbose_name='Reports View')),
                ('reports_edit', models.BooleanField(default=False, verbose_name='Reports Edit')),
                ('users_view', models.BooleanField(default=False, verbose_name='Users View')),
                ('users_edit', models.BooleanField(default=False, verbose_name='Users Edit')),
                ('settings_view', models.BooleanField(default=False, verbose_name='Settings View')),
                ('settings_edit', models.BooleanField(default=False, verbose_name='Settings Edit')),
                ('subjects_view', models.BooleanField(default=False, verbose_name='Subjects View')),
                ('subjects_edit', models.BooleanField(default=False, verbose_name='Subjects Edit')),
                ('messaging_view', models.BooleanField(default=False, verbose_name='Messaging View')),
                ('messaging_edit', models.BooleanField(default=False, verbose_name='Messaging Edit')),
                ('promotion_view', models.BooleanField(default=False, verbose_name='Promotion View')),
                ('promotion_edit', models.BooleanField(default=False, verbose_name='Promotion Edit')),
                ('backup_view', models.BooleanField(default=False, verbose_name='Backup View')),
                ('backup_edit', models.BooleanField(default=False, verbose_name='Backup Edit')),
                ('fines_view', models.BooleanField(default=False, verbose_name='Fines View')),
                ('fines_edit', models.BooleanField(default=False, verbose_name='Fines Edit')),
                ('school_profile_view', models.BooleanField(default=False, verbose_name='School Profile View')),
                ('school_profile_edit', models.BooleanField(default=False, verbose_name='School Profile Edit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Module Permission',
                'verbose_name_plural': 'User Module Permissions',
                'db_table': 'users_module_permissions',
            },
        ),
    ]
