# Generated by Django 5.0.14 on 2025-10-14 16:14

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_number', models.CharField(max_length=20, unique=True, validators=[core.validators.validate_admission_number], verbose_name='Admission Number')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('date_of_admission', models.DateField(verbose_name='Date of Admission')),
                ('aadhaar_number', models.CharField(blank=True, max_length=14, null=True, validators=[core.validators.validate_aadhaar_number])),
                ('pen_number', models.CharField(blank=True, max_length=11, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Sikh', 'Sikh'), ('Other', 'Other')], max_length=20, verbose_name='Religion')),
                ('caste_category', models.CharField(choices=[('General', 'General'), ('BC', 'BC'), ('EBC', 'EBC'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('Other', 'Other')], max_length=20, verbose_name='Caste Category')),
                ('address', models.TextField(verbose_name='Address')),
                ('mobile_number', models.CharField(max_length=10, validators=[core.validators.validate_phone_number], verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('blood_group', models.CharField(choices=[('UNKN', 'UNKN'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, verbose_name='Blood Group')),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='students/images/', validators=[core.validators.validate_file_size, core.validators.validate_file_extension])),
                ('aadhar_card', models.FileField(upload_to='students/documents/', validators=[core.validators.validate_file_size, core.validators.validate_file_extension], verbose_name='Aadhar Card')),
                ('transfer_certificate', models.FileField(upload_to='students/documents/', validators=[core.validators.validate_file_size, core.validators.validate_file_extension], verbose_name='Transfer Certificate')),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived'), ('GRADUATED', 'Graduated')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('status_reason', models.TextField(blank=True, null=True, verbose_name='Status Change Reason')),
                ('status_changed_date', models.DateTimeField(blank=True, null=True, verbose_name='Status Changed Date')),
                ('status_changed_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Changed By')),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='subjects.classsection')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_date', models.DateField()),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number'], name='students_st_admissi_321db4_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_section'], name='students_st_class_s_7fa89d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['created_at'], name='students_st_created_78a19f_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='students_st_first_n_e9466d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['mobile_number'], name='students_st_mobile__e128af_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='students_st_email_e271bc_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['due_amount'], name='students_st_due_amo_db66c7_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_st_status_5e2210_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status', 'class_section'], name='students_st_status_bc79cd_idx'),
        ),
    ]
