# Generated by Django 5.0.14 on 2025-10-14 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fee_management', '0001_initial'),
        ('fees', '0001_initial'),
        ('fines', '0001_initial'),
        ('student_fees', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedfine',
            name='fine_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fines.finetemplate'),
        ),
        migrations.AddField(
            model_name='appliedfine',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_fines', to='students.student'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='applied_fine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fee_management.appliedfine'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='fee_deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='student_fees.feedeposit'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feestype'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_fees', to='students.student'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='student_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fee_management.studentfee'),
        ),
        migrations.AddIndex(
            model_name='appliedfine',
            index=models.Index(fields=['student', 'is_paid'], name='fee_managem_student_311dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedfine',
            index=models.Index(fields=['applied_date'], name='fee_managem_applied_789d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['student', 'is_paid'], name='fee_managem_student_c485f5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['due_date'], name='fee_managem_due_dat_18ec9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together={('student', 'fee_type', 'academic_year')},
        ),
    ]
