# Generated by Django 5.0.14 on 2025-10-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('qualification', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='teacher_resumes/')),
                ('joining_letter', models.FileField(blank=True, null=True, upload_to='teacher_letters/')),
            ],
        ),
    ]
