# Generated by Django 5.0.14 on 2025-10-14 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Student', max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('message_type', models.CharField(choices=[('fee_reminder', 'Fee Reminder'), ('attendance', 'Attendance Alert'), ('general', 'General Notice'), ('exam', 'Exam Notification'), ('event', 'Event Announcement')], default='general', max_length=20)),
                ('template_content', models.TextField(help_text='Use variables like {{ student_name }}, {{ amount }}, etc.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessagingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_name', models.CharField(default='School', max_length=100)),
                ('sender_phone', models.CharField(default='', max_length=15)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MSG91Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_key', models.CharField(help_text='MSG91 Auth Key', max_length=100)),
                ('sender_id', models.CharField(default='TXTLCL', help_text='MSG91 Sender ID', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'MSG91 Configuration',
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(choices=[('SMS', 'SMS')], default='SMS', max_length=10)),
                ('recipient_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ALL_STUDENTS', 'All Students'), ('ALL_TEACHERS', 'All Teachers'), ('CLASS_STUDENTS', 'Class Students')], default='INDIVIDUAL', max_length=20)),
                ('message_content', models.TextField()),
                ('total_recipients', models.IntegerField(default=0)),
                ('successful_sends', models.IntegerField(default=0)),
                ('failed_sends', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('source_module', models.CharField(choices=[('messaging', 'Messaging'), ('student_fees', 'Student Fees'), ('reports', 'Reports'), ('attendance', 'Attendance'), ('transport', 'Transport'), ('fines', 'Fines'), ('system', 'System')], default='messaging', max_length=20)),
                ('recipient_phone', models.CharField(blank=True, max_length=15)),
                ('recipient_name', models.CharField(blank=True, max_length=100)),
                ('msg91_message_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('class_section_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.classsection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
