# Generated by Django 5.0.14 on 2025-10-14 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('academic_year', models.CharField(default='2024-25', max_length=10)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('min_marks', models.IntegerField(blank=True, null=True)),
                ('current_class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_promotion_from', to='subjects.classsection')),
                ('from_class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_from', to='subjects.classsection')),
                ('next_class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_promotion_to', to='subjects.classsection')),
                ('to_class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_to', to='subjects.classsection')),
            ],
            options={
                'unique_together': {('from_class_section', 'to_class_section', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(default='2024-25', max_length=10)),
                ('promotion_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('from_class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_promotions_from', to='subjects.classsection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='students.student')),
                ('to_class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_promotions_to', to='subjects.classsection')),
            ],
            options={
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
