# Generated by Django 5.0.14 on 2025-10-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=32, unique=True)),
                ('demo_started', models.DateTimeField(auto_now_add=True)),
                ('demo_expires', models.DateTimeField()),
                ('is_licensed', models.BooleanField(default=False)),
                ('license_key', models.CharField(blank=True, max_length=200, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Demo Status',
                'verbose_name_plural': 'Demo Statuses',
            },
        ),
        migrations.CreateModel(
            name='LicenseActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key_attempted', models.CharField(max_length=200)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'License Activation',
                'verbose_name_plural': 'License Activations',
            },
        ),
    ]
