# Generated by Django 5.0.14 on 2025-10-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(choices=[('backup', 'Backup'), ('restore', 'Restore')], default='backup', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('failed', 'failed'), ('completed', 'completed')], default='pending', max_length=16)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=16, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('schema_version', models.CharField(blank=True, max_length=32, null=True)),
                ('report_json', models.JSONField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('backup_type', models.CharField(default='full', max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'backup_jobs',
            },
        ),
        migrations.CreateModel(
            name='RestoreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=16)),
                ('source_type', models.CharField(choices=[('backup', 'backup'), ('uploaded', 'uploaded')], default='backup', max_length=16)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=16, null=True)),
                ('mode', models.CharField(choices=[('replace', 'replace'), ('merge', 'merge')], default='merge', max_length=16)),
                ('duplicate_strategy', models.CharField(choices=[('skip', 'skip'), ('update', 'update')], default='update', max_length=16)),
                ('schema_version', models.CharField(blank=True, max_length=32, null=True)),
                ('validation_result_json', models.JSONField(blank=True, null=True)),
                ('report_json', models.JSONField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'restore_jobs',
            },
        ),
        migrations.CreateModel(
            name='ScheduledBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental Backup')], default='full', max_length=20)),
                ('cron_expression', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scheduled_backups',
                'ordering': ['name'],
            },
        ),
    ]
