# Generated by Django 5.0.14 on 2025-10-14 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='restorejob',
            index=models.Index(fields=['created_at'], name='restore_job_created_1966e2_idx'),
        ),
        migrations.AddIndex(
            model_name='restorejob',
            index=models.Index(fields=['status'], name='restore_job_status_c0686d_idx'),
        ),
        migrations.AddField(
            model_name='scheduledbackup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='backupjob',
            index=models.Index(fields=['created_at'], name='backup_jobs_created_932e00_idx'),
        ),
        migrations.AddIndex(
            model_name='backupjob',
            index=models.Index(fields=['status'], name='backup_jobs_status_a40201_idx'),
        ),
    ]
