# D:\School-Management-System\School-Management-System-main\school_management\settings.py
"""
Django settings for school_management project.
Generated by 'django-admin startproject' using Django 5.1.6.
"""
import os
from pathlib import Path
import warnings
from django.core.management.utils import get_random_secret_key

# Ignore warnings
warnings.filterwarnings("ignore", category=UserWarning)

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass

# ======================
# SECURITY SETTINGS
# ======================
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fixed-key-for-development-only-change-in-production-12345')
DEBUG = False #os.environ.get("DEBUG", "False").lower() == "true"
ALLOWED_HOSTS = ['*']#os.environ.get('ALLOWED_HOSTS', '*').split(',')

# Security Headers
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# HTTPS Settings
USE_HTTPS = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
CSRF_TRUSTED_ORIGINS = [
    'https://localhost:9000',
    'https://127.0.0.1:9000',
    'http://localhost:9000',
    'http://127.0.0.1:9000',
    "http://192.168.1.106:9000",
    'https://*.ngrok.io',
    'https://*.ngrok-free.app',
]

# Webhook CSRF exemption
CSRF_EXEMPT_URLS = [r'^messaging/webhook/$']

# ====================== 
# APPLICATION DEFINITION
# ======================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'sslserver',
    'rest_framework',
    'core',  # Add core app first
    'core.fee_management',  # Add centralized fee management
    'users',
    'dashboard',
    'teachers',
    'settings',
    'subjects',
    'students',
    'student_fees',
    'transport',
    'fees',
    "fines",
    'attendance',
    'promotion',
    'reports',
    'backup',
    'school_profile',
    'messaging',
    # 'django_celery_beat',
    # 'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'core.middleware.SecurityMiddleware',  # Temporarily disabled
    'core.middleware.pdf_export.PDFExportMiddleware',  # PDF export fix
    'django.contrib.messages.middleware.MessageMiddleware',
    'users.middleware.ModuleAccessMiddleware',  # Module access control
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'school_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
            BASE_DIR / "fees/templates",
            BASE_DIR / "school_profile/templates",
            BASE_DIR / "settings/templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'school_management.context_processors.academic_session_context',
                'school_profile.context_processors.school_info',
                'users.views.module_permissions_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_management.wsgi.application'

# ======================
# DATABASE
# ======================
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
        'OPTIONS': {
            'timeout': 20,
        } if os.getenv('DB_ENGINE', 'sqlite3') == 'django.db.backends.sqlite3' else {},
    }
}

# ======================
# AUTHENTICATION
# ======================
AUTH_USER_MODEL = 'users.CustomUser'
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 8}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
    {'NAME': 'users.validators.SchoolPasswordValidator'},
    {'NAME': 'users.validators.NoPersonalInfoValidator'},
]
LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGIN_EXEMPT_URLS = [r'^media/']

# ======================
# SESSION CONFIGURATION
# ======================
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_NAME = 'school_sessionid'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# ======================
# INTERNATIONALIZATION
# ======================
LANGUAGE_CODE = 'en'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
LANGUAGES = [
    ('en', 'English'),
    ('hi', 'Hindi'),
]
LOCALE_PATHS = [BASE_DIR / 'locale']

# UTF-8 Encoding Settings
DEFAULT_CHARSET = 'utf-8'
FILE_CHARSET = 'utf-8'

# ======================
# STATIC & MEDIA FILES
# ======================
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_ROOT = os.path.join(BASE_DIR, 'staticfiles', 'root')
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 30  # 30 days cache

# ======================
# LOGGING CONFIGURATION
# ======================
# Enhanced Logging Configuration for Backup System
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'ignore_broken_pipe': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: not ('Broken pipe' in record.getMessage() or 'Connection reset by peer' in record.getMessage()),
        },
    },
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} - {message}',
            'style': '{',
        },
        'backup_detailed': {
            'format': '[{asctime}] {levelname} {name} {funcName}:{lineno} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 15*1024*1024,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'backup_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'backup.log'),
            'maxBytes': 10*1024*1024,  # 10MB
            'backupCount': 5,
            'formatter': 'backup_detailed',
        },
        'backup_security': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'backup_security.log'),
            'maxBytes': 10*1024*1024,  # 10MB
            'backupCount': 5,
            'formatter': 'backup_detailed',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'backup': {
            'handlers': ['backup_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'backup.security': {
            'handlers': ['backup_security', 'backup_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'backup.audit': {
            'handlers': ['backup_security'],
            'level': 'INFO',
            'propagate': False,
        },
        'backup.performance': {
            'handlers': ['backup_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'backup.monitoring': {
            'handlers': ['backup_file', 'backup_security'],
            'level': 'INFO',
            'propagate': False,
        },
        'export': {
            'handlers': ['backup_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'export.api': {
            'handlers': ['backup_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'urllib3.connectionpool': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Ensure log directory exists
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# ======================
# FILE UPLOAD SETTINGS
# ======================
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
DATA_UPLOAD_MAX_MEMORY_SIZE = FILE_UPLOAD_MAX_MEMORY_SIZE
FILE_UPLOAD_MAX_SIZE = FILE_UPLOAD_MAX_MEMORY_SIZE
ALLOWED_FILE_TYPES = ['pdf', 'jpg', 'jpeg', 'png', 'gif', 'doc', 'docx', 'json', 'sqlite3']

# ======================
# EMAIL CONFIGURATION
# ======================
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ======================
# THIRD PARTY SETTINGS
# ======================

# ======================
# CELERY CONFIGURATION
# ======================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ======================
# OTHER SETTINGS
# ======================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# ======================
# REST FRAMEWORK SETTINGS
# ======================
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}


# Additional Security Settings
if not DEBUG:
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Backup System Configuration (Added by backup_security_fixes.py)
BACKUP_MAX_FILE_SIZE = int(os.getenv('BACKUP_MAX_FILE_SIZE', 50 * 1024 * 1024))  # 50MB
BACKUP_RETENTION_DAYS = int(os.getenv('BACKUP_RETENTION_DAYS', 30))
BACKUP_COMPRESSION_ENABLED = os.getenv('BACKUP_COMPRESSION_ENABLED', 'True').lower() == 'true'
BACKUP_ENCRYPTION_ENABLED = os.getenv('BACKUP_ENCRYPTION_ENABLED', 'False').lower() == 'true'
BACKUP_ENCRYPTION_KEY = os.getenv('BACKUP_ENCRYPTION_KEY')
BACKUP_ASYNC_ENABLED = os.getenv('BACKUP_ASYNC_ENABLED', 'True').lower() == 'true'
BACKUP_MAX_CONCURRENT_OPERATIONS = int(os.getenv('BACKUP_MAX_CONCURRENT_OPERATIONS', 3))
BACKUP_CHUNK_SIZE = int(os.getenv('BACKUP_CHUNK_SIZE', 1000))
BACKUP_HEALTH_CHECK_INTERVAL = int(os.getenv('BACKUP_HEALTH_CHECK_INTERVAL', 3600))
BACKUP_ALERT_EMAIL_ENABLED = os.getenv('BACKUP_ALERT_EMAIL_ENABLED', 'True').lower() == 'true'
BACKUP_METRICS_RETENTION_HOURS = int(os.getenv('BACKUP_METRICS_RETENTION_HOURS', 168))
BACKUP_DIRECTORY = os.getenv('BACKUP_DIRECTORY', os.path.join(BASE_DIR, 'backups'))
BACKUP_TEMP_DIRECTORY = os.getenv('BACKUP_TEMP_DIRECTORY', os.path.join(BASE_DIR, 'backups', 'temp'))
BACKUP_CLEANUP_ENABLED = os.getenv('BACKUP_CLEANUP_ENABLED', 'True').lower() == 'true'
BACKUP_MAX_BACKUPS_PER_TYPE = int(os.getenv('BACKUP_MAX_BACKUPS_PER_TYPE', 50))

# Security Settings for Backup Operations
SECURE_BACKUP_OPERATIONS = True
BACKUP_REQUIRE_HTTPS = not DEBUG
BACKUP_SESSION_TIMEOUT = 3600  # 1 hour
BACKUP_MAX_LOGIN_ATTEMPTS = 5
BACKUP_LOCKOUT_DURATION = 900  # 15 minutes


# Enhanced Cache Configuration for Backup Rate Limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'backup-cache',
        'TIMEOUT': 3600,
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
            'CULL_FREQUENCY': 3,
        }
    }
}

# Session Configuration for Backup Security
SESSION_COOKIE_AGE = BACKUP_SESSION_TIMEOUT
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Backup monitoring middleware disabled temporarily
# if 'backup.monitoring.BackupMonitoringMiddleware' not in MIDDLEWARE:
#     MIDDLEWARE = MIDDLEWARE + ['backup.monitoring.BackupMonitoringMiddleware']