# Generated by Django 5.0.14 on 2025-10-14 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Route Name')),
            ],
        ),
        migrations.CreateModel(
            name='Stoppage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Stoppage Name')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route', verbose_name='Route')),
            ],
            options={
                'unique_together': {('route', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TransportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route', verbose_name='Route')),
                ('stoppage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.stoppage', verbose_name='Stoppage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transportassignment',
            constraint=models.UniqueConstraint(fields=('student',), name='unique_student_per_route'),
        ),
    ]
